version: '3.8'

services:
  carla-server:
    image: carlasim/carla:0.9.14
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - DISPLAY=${DISPLAY}
    ports:
      - "2000:2000"
      - "2001:2001"
      - "2002:2002"
    command: /bin/bash CarlaUE4.sh -world-port=2000 -resx=800 -resy=600 -quality-level=Low
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    network_mode: host

  yolop-simulation:
    build: .
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_DOMAIN_ID=0
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./saved_images:/ros2_ws/saved_images
    depends_on:
      - carla-server
    network_mode: host
    stdin_open: true
    tty: true
    command: bash -c "sleep 15 && ros2 launch av_sim_core spawn_and_perception.launch.py"
